{{- if eq .Values.installMode "default" -}}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ template "dataops.namespace" . }}

---

apiVersion: v1
kind: Namespace
metadata:
  name: {{ template "aiops.namespace" . }}

--- 

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sreworks-base-role
  namespace: {{ template "dataops.namespace" . }}
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps.abm.io"]
  resources: ["*"]
  verbs: ["*"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sreworks-base-role
  namespace: {{ template "aiops.namespace" . }}
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps.abm.io"]
  resources: ["*"]
  verbs: ["*"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sreworks-base-rolebinding
  namespace: {{ template "aiops.namespace" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sreworks-base-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Release.Namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sreworks-base-rolebinding
  namespace: {{ template "dataops.namespace" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sreworks-base-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Release.Namespace }}


{{- end -}}
