{{- if eq .Values.installMode "default" -}}

{{ if .Values.progressCheck }}

apiVersion: batch/v1
kind: Job
metadata: 
  name: sreworks-progress-check
spec:
  backoffLimit: 100000
  ttlSecondsAfterFinished: 600
  template:
    spec:
      serviceAccountName: appmanager-account
      restartPolicy: OnFailure 
      containers:
      - image: {{ template "images.progressCheck" . }}
        name: job
        imagePullPolicy: {{ .Values.global.images.imagePullPolicy }}
        envFrom:
          - configMapRef:
              name: init-configmap
 
{{ end }}


{{- end -}}
